spring:
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


app:
  batch-size: 1000
  thread-count: 4
  products-file: products.csv
  date-format: yyyyMMdd