spring:
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


app:
  batch-size: 20000
  thread-count: 2
  products-file: products.csv
  date-format: yyyyMMdd

server:
  port: 8081